name: flex
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.20
      - pandas>=2.0
      - scipy>=1.10
      - tqdm>=4.66
      - bed-reader<=1.0
      - matplotlib>=3.7
      - scikit-learn>=1.3
      - statsmodels>=0.14
      - chi2comb>=0.1
