name: "Tests on Ubuntu"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Tests on Ubuntu
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - cxx: "clang++-13"
            build-type: "Debug"
          - cxx: "clang++-14"
            build-type: "Release"
          - cxx: "g++-10"
            build-type: "Release"
          - cxx: "g++-12"
            build-type: "Debug"

    env:
      CXX: ${{ matrix.cxx }}
      BUILD_DIR: ${{ github.workspace }}/build_dir
      TEST_OUTPUT_DIR: ${{ github.workspace }}/test_output
      EXAMPLE_DIR: ${{ github.workspace }}/example

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install system packages
        run: |
          sudo apt -y update
          sudo apt -y install libboost-dev libgsl-dev

      - name: make directories
        run: |
          mkdir build_dir
          mkdir test_output
          ls -la

      - name: cmake configure
        run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
        working-directory: ${{ env.BUILD_DIR }}

      - name: cmake build
        run: cmake --build . --parallel 4
        working-directory: ${{ env.BUILD_DIR }}

      - name: test GENIE
        run: |
          gen=${EXAMPLE_DIR}/test
          phen=${EXAMPLE_DIR}/test.pheno
          covar=${EXAMPLE_DIR}/test.cov
          annot=${EXAMPLE_DIR}/single.annot
          env=${EXAMPLE_DIR}/test.env
          ./GENIE -g $gen -p $phen -c $covar -e $env -m G+GxE+NxE  -k 10 -jn 10  -o ${TEST_OUTPUT_DIR}/test.out -annot $annot -t 6
          cat ${TEST_OUTPUT_DIR}/test.out
        working-directory: ${{ env.BUILD_DIR }}
